//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BugInfoManagement_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BugInfoManagement_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamView.BugInfoManagement.Resource", typeof(BugInfoManagement_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string AddBugInfoFormName {
            get {
                return ResourceManager.GetString("AddBugInfoFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficult Assessment:.
        /// </summary>
        internal static string BIAssessment {
            get {
                return ResourceManager.GetString("BIAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug Dealer:.
        /// </summary>
        internal static string BIBugDealMan {
            get {
                return ResourceManager.GetString("BIBugDealMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string BIBugDescription {
            get {
                return ResourceManager.GetString("BIBugDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug Num:.
        /// </summary>
        internal static string BIBugNum {
            get {
                return ResourceManager.GetString("BIBugNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        internal static string BIBugState {
            get {
                return ResourceManager.GetString("BIBugState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creater:.
        /// </summary>
        internal static string BICreater {
            get {
                return ResourceManager.GetString("BICreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal Record:.
        /// </summary>
        internal static string BIDealRecord {
            get {
                return ResourceManager.GetString("BIDealRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Assessment(H):.
        /// </summary>
        internal static string BIPreTakeTime {
            get {
                return ResourceManager.GetString("BIPreTakeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority:.
        /// </summary>
        internal static string BIPriority {
            get {
                return ResourceManager.GetString("BIPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time consuming(H):.
        /// </summary>
        internal static string BITakeTime {
            get {
                return ResourceManager.GetString("BITakeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string BIVersionNum {
            get {
                return ResourceManager.GetString("BIVersionNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug Dealer.
        /// </summary>
        internal static string dBugDealer {
            get {
                return ResourceManager.GetString("dBugDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug Number.
        /// </summary>
        internal static string dBugNum {
            get {
                return ResourceManager.GetString("dBugNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal Record.
        /// </summary>
        internal static string dDealRecord {
            get {
                return ResourceManager.GetString("dDealRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string dDescription {
            get {
                return ResourceManager.GetString("dDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string dPriority {
            get {
                return ResourceManager.GetString("dPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string dSize {
            get {
                return ResourceManager.GetString("dSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string dState {
            get {
                return ResourceManager.GetString("dState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string dVersion {
            get {
                return ResourceManager.GetString("dVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit The Bug.
        /// </summary>
        internal static string EditBugInfoFormName {
            get {
                return ResourceManager.GetString("EditBugInfoFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate by:.
        /// </summary>
        internal static string estimatedByLabel {
            get {
                return ResourceManager.GetString("estimatedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string mAbortButton {
            get {
                return ResourceManager.GetString("mAbortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string mAddButton {
            get {
                return ResourceManager.GetString("mAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamView.
        /// </summary>
        internal static string MainFormName {
            get {
                return ResourceManager.GetString("MainFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Information.
        /// </summary>
        internal static string mBaseInfoGroupBox {
            get {
                return ResourceManager.GetString("mBaseInfoGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string mBoldButton {
            get {
                return ResourceManager.GetString("mBoldButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug Num:.
        /// </summary>
        internal static string mBugNumberLabel {
            get {
                return ResourceManager.GetString("mBugNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string mCompleteButton {
            get {
                return ResourceManager.GetString("mCompleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programer:.
        /// </summary>
        internal static string mDealManlabel {
            get {
                return ResourceManager.GetString("mDealManlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string mDescriptionLabel {
            get {
                return ResourceManager.GetString("mDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string mDoAddButton {
            get {
                return ResourceManager.GetString("mDoAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string mEditButton {
            get {
                return ResourceManager.GetString("mEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state can&apos;t be changed ！.
        /// </summary>
        internal static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one task&apos;s state can be Dealing at one time ！.
        /// </summary>
        internal static string Message2 {
            get {
                return ResourceManager.GetString("Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data has been out of the time ！.
        /// </summary>
        internal static string Message3 {
            get {
                return ResourceManager.GetString("Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please chose one record what you want to edit！！！.
        /// </summary>
        internal static string Message4 {
            get {
                return ResourceManager.GetString("Message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete！.
        /// </summary>
        internal static string Message5 {
            get {
                return ResourceManager.GetString("Message5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record has been deleted ！.
        /// </summary>
        internal static string Message6 {
            get {
                return ResourceManager.GetString("Message6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Message.
        /// </summary>
        internal static string Message7 {
            get {
                return ResourceManager.GetString("Message7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please chose one record which you want to delete ！.
        /// </summary>
        internal static string Message8 {
            get {
                return ResourceManager.GetString("Message8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bug Num can&apos;t be null ！.
        /// </summary>
        internal static string MessageBugNum {
            get {
                return ResourceManager.GetString("MessageBugNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Creater Can&apos;t be null ！.
        /// </summary>
        internal static string MessageCreater {
            get {
                return ResourceManager.GetString("MessageCreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Version can&apos;t be null ！.
        /// </summary>
        internal static string MessageVersion {
            get {
                return ResourceManager.GetString("MessageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string mFeedBackSection {
            get {
                return ResourceManager.GetString("mFeedBackSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        internal static string mGrayButton {
            get {
                return ResourceManager.GetString("mGrayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string mMaxButtonText1 {
            get {
                return ResourceManager.GetString("mMaxButtonText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string mMaxButtonText2 {
            get {
                return ResourceManager.GetString("mMaxButtonText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string mNormalButton {
            get {
                return ResourceManager.GetString("mNormalButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string mQueryButton {
            get {
                return ResourceManager.GetString("mQueryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Condition.
        /// </summary>
        internal static string mQueryGroupBox {
            get {
                return ResourceManager.GetString("mQueryGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string mQuitButton {
            get {
                return ResourceManager.GetString("mQuitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string mSectionButton {
            get {
                return ResourceManager.GetString("mSectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string mStartButton {
            get {
                return ResourceManager.GetString("mStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        internal static string mStateLabel {
            get {
                return ResourceManager.GetString("mStateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string mVersionNumber {
            get {
                return ResourceManager.GetString("mVersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points:.
        /// </summary>
        internal static string pointsLabel {
            get {
                return ResourceManager.GetString("pointsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Records.
        /// </summary>
        internal static string TotalRecord {
            get {
                return ResourceManager.GetString("TotalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time.
        /// </summary>
        internal static string TotalTime {
            get {
                return ResourceManager.GetString("TotalTime", resourceCulture);
            }
        }
    }
}
