using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL
{
	/// <summary>
	/// Strongly-typed collection for the BugDoc class.
	/// </summary>
    [Serializable]
	public partial class BugDocCollection : ActiveList<BugDoc, BugDocCollection>
	{	   
		public BugDocCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>BugDocCollection</returns>
		public BugDocCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                BugDoc o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the bugDoc table.
	/// </summary>
	[Serializable]
	public partial class BugDoc : ActiveRecord<BugDoc>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public BugDoc()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public BugDoc(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public BugDoc(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public BugDoc(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("bugDoc", TableType.Table, DataService.GetInstance("BugInfoProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarBugNum = new TableSchema.TableColumn(schema);
				colvarBugNum.ColumnName = "bugNum";
				colvarBugNum.DataType = DbType.AnsiString;
				colvarBugNum.MaxLength = 20;
				colvarBugNum.AutoIncrement = false;
				colvarBugNum.IsNullable = false;
				colvarBugNum.IsPrimaryKey = true;
				colvarBugNum.IsForeignKey = false;
				colvarBugNum.IsReadOnly = false;
				colvarBugNum.DefaultSetting = @"";
				colvarBugNum.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBugNum);
				
				TableSchema.TableColumn colvarDoc = new TableSchema.TableColumn(schema);
				colvarDoc.ColumnName = "Doc";
				colvarDoc.DataType = DbType.Binary;
				colvarDoc.MaxLength = 2147483647;
				colvarDoc.AutoIncrement = false;
				colvarDoc.IsNullable = true;
				colvarDoc.IsPrimaryKey = false;
				colvarDoc.IsForeignKey = false;
				colvarDoc.IsReadOnly = false;
				colvarDoc.DefaultSetting = @"";
				colvarDoc.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDoc);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["BugInfoProvider"].AddSchema("bugDoc",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("BugNum")]
		[Bindable(true)]
		public string BugNum 
		{
			get { return GetColumnValue<string>(Columns.BugNum); }
			set { SetColumnValue(Columns.BugNum, value); }
		}
		  
		[XmlAttribute("Doc")]
		[Bindable(true)]
		public byte[] Doc 
		{
			get { return GetColumnValue<byte[]>(Columns.Doc); }
			set { SetColumnValue(Columns.Doc, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varBugNum,byte[] varDoc)
		{
			BugDoc item = new BugDoc();
			
			item.BugNum = varBugNum;
			
			item.Doc = varDoc;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(string varBugNum,byte[] varDoc)
		{
			BugDoc item = new BugDoc();
			
				item.BugNum = varBugNum;
			
				item.Doc = varDoc;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn BugNumColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn DocColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string BugNum = @"bugNum";
			 public static string Doc = @"Doc";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
