using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL
{
    /// <summary>
    /// Controller class for ChangeLog
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ChangeLogController
    {
        // Preload our schema..
        ChangeLog thisSchemaLoad = new ChangeLog();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ChangeLogCollection FetchAll()
        {
            ChangeLogCollection coll = new ChangeLogCollection();
            Query qry = new Query(ChangeLog.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ChangeLogCollection FetchByID(object LogID)
        {
            ChangeLogCollection coll = new ChangeLogCollection().Where("LogID", LogID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ChangeLogCollection FetchByQuery(Query qry)
        {
            ChangeLogCollection coll = new ChangeLogCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object LogID)
        {
            return (ChangeLog.Delete(LogID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object LogID)
        {
            return (ChangeLog.Destroy(LogID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string BugNum,DateTime CreateDate,string Description,int LogTypeID)
	    {
		    ChangeLog item = new ChangeLog();
		    
            item.BugNum = BugNum;
            
            item.CreateDate = CreateDate;
            
            item.Description = Description;
            
            item.LogTypeID = LogTypeID;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(long LogID,string BugNum,DateTime CreateDate,string Description,int LogTypeID)
	    {
		    ChangeLog item = new ChangeLog();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.LogID = LogID;
				
			item.BugNum = BugNum;
				
			item.CreateDate = CreateDate;
				
			item.Description = Description;
				
			item.LogTypeID = LogTypeID;
				
	        item.Save(UserName);
	    }
    }
}
