using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL
{
    /// <summary>
    /// Controller class for keyInfo
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class KeyInfoController
    {
        // Preload our schema..
        KeyInfo thisSchemaLoad = new KeyInfo();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public KeyInfoCollection FetchAll()
        {
            KeyInfoCollection coll = new KeyInfoCollection();
            Query qry = new Query(KeyInfo.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public KeyInfoCollection FetchByID(object KeyName)
        {
            KeyInfoCollection coll = new KeyInfoCollection().Where("keyName", KeyName).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public KeyInfoCollection FetchByQuery(Query qry)
        {
            KeyInfoCollection coll = new KeyInfoCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object KeyName)
        {
            return (KeyInfo.Delete(KeyName) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object KeyName)
        {
            return (KeyInfo.Destroy(KeyName) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string KeyName,long Num)
	    {
		    KeyInfo item = new KeyInfo();
		    
            item.KeyName = KeyName;
            
            item.Num = Num;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(string KeyName,long Num)
	    {
		    KeyInfo item = new KeyInfo();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.KeyName = KeyName;
				
			item.Num = Num;
				
	        item.Save(UserName);
	    }
    }
}
